### ISSUE TITLE
Running transformation prior to the type checking phase

### ISSUE THREAD

**Issue by TomasHubelbauer** [Zoltu/typescript-transformer-append-js-extension#13]
Hi, this is not an issue or a question about your transform, but I have used it as a basis (or rather, completely ripped it off for) a transformation of my own. My goal is to mutate the import statements so that any relative paths which also happen to include URL `?search` or `#fragment` parts do not contain these parts from the TypeScript's PoV. I want to make them invisible for TypeScript.

I have succeeded in straight up removing these bits in the import statements:
https://github.com/TomasHubelbauer/ttypescript-esm

However, when I run the plugin, it seems to happen after the type checking phase and only before the emitting phase. When I run `npx ttsc index.ts`, I still receive this error:

```
index.ts:1:17 - error TS2307: Cannot find module './mod?test' or its corresponding type declarations.

1 import mod from './mod?test';
                  ~~~~~~~~~~~~
```

I am wondering if you might know how to make the transformation run prior to the type checking phase, so that this error is avoided.

I also do not care about the emit phase, I actually want this for type-checking of JavaScript projects (so that TypeScript doesn't lose track of types across the import boundary, like it doesn't with imports which don't contain search/fragment URL part) and will not be using it with TypeScript projects. I will instead use this with the VS Code language service so that VS Code type-checks my JavaScript project with ttypescript and doesn't flag this error as an issue and doesn't lose track of types across the module boundary once I'm able to get this transformation to work prior to the type-checking phase.

If you'd like me to ask directly in the ttypescript issues, let me know, I figured I'd try here as you've written a very, very similar transformation to what I think I need to do, but I understand you might not be interested in debugging other people's transforms. Thank you

**Comment by MicahZoltu** [comment]
I think what you want is to change `after: true` to `after: false` in your `tsconfig.json`.  That determines when in the lifecycle the transformer is executed, and it sounds like you want your transformer to execute early in the lifecycle.  For further details on controlling *when* a transformer is executed, the `ttypescript` project would be a better place to ask though.  😄 

```json
"plugins": [
	{
		"transform": "@zoltu/typescript-transformer-append-js-extension/output/index.js",
		"after": true, // <--- change this to false
	}
]
```

**Comment by TomasHubelbauer** [comment]
I did not have this field at all and I assume it was false by default. I tried setting it to an explicit false, but still the same result. I'll take this to the ttypescript project, thanks a lot for looking into this!
