### ISSUE TITLE
Why only relative paths?

### ISSUE THREAD

**Issue by trusktr** [Zoltu/typescript-transformer-append-js-extension#8]
https://github.com/Zoltu/typescript-transformer-append-js-extension/blob/3df3f7885bd1c96337c72974f44dbba017cf9097/source/index.ts#L25

Isn't `/path/to/something.js` a valid import specifier?

**Comment by MicahZoltu** [comment]
Module names are handled very differently from relative imports.  I'm actually not sure how absolute paths are handled.  If you can verify that absolute paths are treated similar to relative paths in browser when it comes to importing let me know and I can update the check to include absolute paths.

I have never tried `import ... from '/path/to/something.js'` in a browser so I honestly have no idea what it does!

**Comment by trusktr** [comment]
It follows same rules as browser URLs: it points to the file from the root of the origin.

If you're on `https://some-domain.com` and your code has `import ... from '/path/to/something.js'`, then the browser will make an HTTP request to `https://some-domain.com/path/to/something.js`

**Comment by trusktr** [comment]
Hmm, but TypeScript may treat is as absolute relative to the file system? That may be a problem.

**Comment by MicahZoltu** [comment]
@trusktr Sorry for the delay in responding to this.  A quick test suggests that absolute imports will not work the way you want out of the box.
```typescirpt
// <root>/apple.ts
export class Apple {}

// <root>/index.ts
import { Apple } from '/apple'

// <root>/tsconfig.json
{
	"compilerOptions": {
		"target": "esnext",
		"module": "commonjs",
		"moduleResolution": "node",
		"strict": true,
		"noEmit": true,
	},
}
```

I also tried with `moduleResolution: classic` and `module: es2015` but the error persisted.

If you can figure out a way to make absolute paths "do the right thing" I'm open to further discussion on how to add support to them here, but for now I don't see an obvious way to integrate them properly.

**Comment by MicahZoltu** [comment]
Closing for now since there isn't an obvious path forward, and barring a solution changes to this area are unlikely to happen.  Feel free to re-open this to continue the discussion or if you have an idea for a complete solution that won't just change "who gets broken".
